apiVersion: v1
kind: ConfigMap
metadata:
  name: inspi-ai-config
  namespace: inspi-ai
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "mysql-primary-service"
  DB_PORT: "3306"
  DB_NAME: "inspi_ai_prod"
  DB_USER: "inspi_user"
  DB_REPLICA_1_HOST: "mysql-replica-1-service"
  DB_REPLICA_2_HOST: "mysql-replica-2-service"
  REDIS_HOST: "redis-cluster-service"
  REDIS_PORT: "7000"
  MONITORING_ENABLED: "true"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  CACHE_MEMORY_MAX_SIZE: "512"
  CACHE_MEMORY_TTL: "300"
  CACHE_REDIS_TTL: "1800"
  RATE_LIMIT_WINDOW: "900000"
  RATE_LIMIT_MAX: "100"
  COMPRESSION_ENABLED: "true"
  COMPRESSION_LEVEL: "6"
  STATIC_MAX_AGE: "31536000"
  ENABLE_GZIP: "true"
  ENABLE_BROTLI: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: inspi-ai
data:
  my.cnf: |
    [mysqld]
    # 基础配置
    bind-address = 0.0.0.0
    port = 3306
    datadir = /var/lib/mysql
    socket = /var/run/mysqld/mysqld.sock
    pid-file = /var/run/mysqld/mysqld.pid
    
    # 字符集
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    
    # InnoDB配置
    innodb_buffer_pool_size = 1G
    innodb_log_file_size = 256M
    innodb_log_buffer_size = 16M
    innodb_flush_log_at_trx_commit = 1
    innodb_file_per_table = 1
    innodb_open_files = 400
    
    # 连接配置
    max_connections = 1000
    max_connect_errors = 1000
    wait_timeout = 28800
    interactive_timeout = 28800
    
    # 查询缓存
    query_cache_size = 0
    query_cache_type = 0
    
    # 慢查询日志
    slow_query_log = 1
    slow_query_log_file = /var/log/mysql/slow.log
    long_query_time = 2
    log_queries_not_using_indexes = 1
    
    # 二进制日志
    log-bin = mysql-bin
    binlog_format = ROW
    expire_logs_days = 7
    max_binlog_size = 100M
    
    # GTID
    gtid-mode = ON
    enforce-gtid-consistency = ON
    log-slave-updates = ON
    
    # 安全配置
    skip-name-resolve
    local-infile = 0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: inspi-ai
data:
  redis.conf: |
    # 网络配置
    bind 0.0.0.0
    protected-mode no
    port 7000
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    
    # 通用配置
    daemonize no
    supervised no
    pidfile /var/run/redis_7000.pid
    loglevel notice
    logfile ""
    databases 16
    
    # 持久化配置
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir ./
    
    # AOF配置
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    
    # 集群配置
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    cluster-announce-ip 0.0.0.0
    cluster-announce-port 7000
    cluster-announce-bus-port 17000
    
    # 内存配置
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    
    # 客户端配置
    maxclients 10000