apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-primary-pvc
  namespace: inspi-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-replica-1-pvc
  namespace: inspi-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-replica-2-pvc
  namespace: inspi-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-primary
  namespace: inspi-ai
  labels:
    app: mysql-primary
spec:
  serviceName: mysql-primary-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql-primary
  template:
    metadata:
      labels:
        app: mysql-primary
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inspi-ai-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "inspi_ai_prod"
        - name: MYSQL_USER
          value: "inspi_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inspi-ai-secrets
              key: DB_PASSWORD
        - name: MYSQL_REPLICATION_USER
          value: "replicator"
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inspi-ai-secrets
              key: MYSQL_REPLICATION_PASSWORD
        args:
        - --server-id=1
        - --log-bin=mysql-bin
        - --binlog-format=ROW
        - --gtid-mode=ON
        - --enforce-gtid-consistency=ON
        - --log-slave-updates=ON
        - --binlog-do-db=inspi_ai_prod
        - --innodb-buffer-pool-size=1G
        - --innodb-log-file-size=256M
        - --max-connections=1000
        - --query-cache-size=0
        - --query-cache-type=0
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -e
            - "SELECT 1"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-primary-pvc
      - name: mysql-config
        configMap:
          name: mysql-config

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-primary-service
  namespace: inspi-ai
  labels:
    app: mysql-primary
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql-primary

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica-1
  namespace: inspi-ai
  labels:
    app: mysql-replica-1
spec:
  serviceName: mysql-replica-1-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql-replica-1
  template:
    metadata:
      labels:
        app: mysql-replica-1
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inspi-ai-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "inspi_ai_prod"
        - name: MYSQL_USER
          value: "inspi_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inspi-ai-secrets
              key: DB_PASSWORD
        args:
        - --server-id=2
        - --log-bin=mysql-bin
        - --binlog-format=ROW
        - --gtid-mode=ON
        - --enforce-gtid-consistency=ON
        - --log-slave-updates=ON
        - --read-only=1
        - --super-read-only=1
        - --innodb-buffer-pool-size=512M
        - --max-connections=500
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -e
            - "SELECT 1"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-replica-1-pvc
      - name: mysql-config
        configMap:
          name: mysql-config

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica-1-service
  namespace: inspi-ai
  labels:
    app: mysql-replica-1
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql-replica-1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica-2
  namespace: inspi-ai
  labels:
    app: mysql-replica-2
spec:
  serviceName: mysql-replica-2-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql-replica-2
  template:
    metadata:
      labels:
        app: mysql-replica-2
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inspi-ai-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "inspi_ai_prod"
        - name: MYSQL_USER
          value: "inspi_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inspi-ai-secrets
              key: DB_PASSWORD
        args:
        - --server-id=3
        - --log-bin=mysql-bin
        - --binlog-format=ROW
        - --gtid-mode=ON
        - --enforce-gtid-consistency=ON
        - --log-slave-updates=ON
        - --read-only=1
        - --super-read-only=1
        - --innodb-buffer-pool-size=512M
        - --max-connections=500
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysql
            - -h
            - localhost
            - -e
            - "SELECT 1"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-replica-2-pvc
      - name: mysql-config
        configMap:
          name: mysql-config

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica-2-service
  namespace: inspi-ai
  labels:
    app: mysql-replica-2
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql-replica-2