# 基础设施告警规则
groups:
  - name: infrastructure.rules
    rules:
      # 主机可用性告警
      - alert: HostDown
        expr: up{job="node-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "主机不可用"
          description: "主机 {{ $labels.instance }} 已经停止响应超过1分钟"
          runbook_url: "https://docs.inspi.ai/runbooks/host-down"

      # 主机CPU使用率告警
      - alert: HostHighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "主机CPU使用率过高"
          description: "主机 {{ $labels.instance }} CPU使用率超过80%，当前值: {{ $value }}%"
          runbook_url: "https://docs.inspi.ai/runbooks/host-high-cpu-usage"

      # 主机内存使用率告警
      - alert: HostHighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "主机内存使用率过高"
          description: "主机 {{ $labels.instance }} 内存使用率超过85%，当前值: {{ $value }}%"
          runbook_url: "https://docs.inspi.ai/runbooks/host-high-memory-usage"

      # 主机磁盘使用率告警
      - alert: HostHighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "主机磁盘使用率过高"
          description: "主机 {{ $labels.instance }} 磁盘 {{ $labels.mountpoint }} 使用率超过85%，当前值: {{ $value }}%"
          runbook_url: "https://docs.inspi.ai/runbooks/host-high-disk-usage"

      # 主机磁盘空间严重不足
      - alert: HostCriticalDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 95
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "主机磁盘空间严重不足"
          description: "主机 {{ $labels.instance }} 磁盘 {{ $labels.mountpoint }} 使用率超过95%，当前值: {{ $value }}%"
          runbook_url: "https://docs.inspi.ai/runbooks/host-critical-disk-usage"

      # 主机负载告警
      - alert: HostHighLoad
        expr: node_load15 / count by(instance) (node_cpu_seconds_total{mode="idle"}) > 1.5
        for: 10m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "主机负载过高"
          description: "主机 {{ $labels.instance }} 15分钟平均负载超过CPU核心数的1.5倍，当前值: {{ $value }}"
          runbook_url: "https://docs.inspi.ai/runbooks/host-high-load"

      # 网络连接数告警
      - alert: HostHighNetworkConnections
        expr: node_netstat_Tcp_CurrEstab > 5000
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "主机网络连接数过高"
          description: "主机 {{ $labels.instance }} TCP连接数超过5000，当前值: {{ $value }}"
          runbook_url: "https://docs.inspi.ai/runbooks/host-high-network-connections"

  - name: database.rules
    rules:
      # MySQL可用性告警
      - alert: MySQLDown
        expr: mysql_up == 0
        for: 1m
        labels:
          severity: critical
          category: database
        annotations:
          summary: "MySQL数据库不可用"
          description: "MySQL实例 {{ $labels.instance }} 已经停止响应超过1分钟"
          runbook_url: "https://docs.inspi.ai/runbooks/mysql-down"

      # MySQL连接数告警
      - alert: MySQLHighConnections
        expr: mysql_global_status_threads_connected / mysql_global_variables_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "MySQL连接数过高"
          description: "MySQL实例 {{ $labels.instance }} 连接数使用率超过80%，当前值: {{ $value }}%"
          runbook_url: "https://docs.inspi.ai/runbooks/mysql-high-connections"

      # MySQL慢查询告警
      - alert: MySQLHighSlowQueries
        expr: rate(mysql_global_status_slow_queries[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "MySQL慢查询过多"
          description: "MySQL实例 {{ $labels.instance }} 慢查询频率超过0.1/秒，当前值: {{ $value }}/秒"
          runbook_url: "https://docs.inspi.ai/runbooks/mysql-high-slow-queries"

      # MySQL复制延迟告警
      - alert: MySQLReplicationLag
        expr: mysql_slave_lag_seconds > 30
        for: 2m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "MySQL复制延迟过高"
          description: "MySQL从库 {{ $labels.instance }} 复制延迟超过30秒，当前值: {{ $value }}秒"
          runbook_url: "https://docs.inspi.ai/runbooks/mysql-replication-lag"

      # MySQL复制中断告警
      - alert: MySQLReplicationStopped
        expr: mysql_slave_sql_running == 0 or mysql_slave_io_running == 0
        for: 1m
        labels:
          severity: critical
          category: database
        annotations:
          summary: "MySQL复制已停止"
          description: "MySQL从库 {{ $labels.instance }} 复制线程已停止"
          runbook_url: "https://docs.inspi.ai/runbooks/mysql-replication-stopped"

  - name: redis.rules
    rules:
      # Redis可用性告警
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          category: cache
        annotations:
          summary: "Redis不可用"
          description: "Redis实例 {{ $labels.instance }} 已经停止响应超过1分钟"
          runbook_url: "https://docs.inspi.ai/runbooks/redis-down"

      # Redis内存使用率告警
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: cache
        annotations:
          summary: "Redis内存使用率过高"
          description: "Redis实例 {{ $labels.instance }} 内存使用率超过85%，当前值: {{ $value }}%"
          runbook_url: "https://docs.inspi.ai/runbooks/redis-high-memory-usage"

      # Redis连接数告警
      - alert: RedisHighConnections
        expr: redis_connected_clients > 1000
        for: 5m
        labels:
          severity: warning
          category: cache
        annotations:
          summary: "Redis连接数过高"
          description: "Redis实例 {{ $labels.instance }} 连接数超过1000，当前值: {{ $value }}"
          runbook_url: "https://docs.inspi.ai/runbooks/redis-high-connections"

      # Redis键过期率告警
      - alert: RedisHighKeyEvictionRate
        expr: rate(redis_evicted_keys_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          category: cache
        annotations:
          summary: "Redis键过期率过高"
          description: "Redis实例 {{ $labels.instance }} 键过期率超过10/秒，当前值: {{ $value }}/秒"
          runbook_url: "https://docs.inspi.ai/runbooks/redis-high-key-eviction-rate"

  - name: nginx.rules
    rules:
      # Nginx可用性告警
      - alert: NginxDown
        expr: nginx_up == 0
        for: 1m
        labels:
          severity: critical
          category: loadbalancer
        annotations:
          summary: "Nginx不可用"
          description: "Nginx实例 {{ $labels.instance }} 已经停止响应超过1分钟"
          runbook_url: "https://docs.inspi.ai/runbooks/nginx-down"

      # Nginx高错误率告警
      - alert: NginxHighErrorRate
        expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) / rate(nginx_http_requests_total[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
          category: loadbalancer
        annotations:
          summary: "Nginx错误率过高"
          description: "Nginx实例 {{ $labels.instance }} 5xx错误率超过5%，当前值: {{ $value | humanizePercentage }}"
          runbook_url: "https://docs.inspi.ai/runbooks/nginx-high-error-rate"

      # Nginx高连接数告警
      - alert: NginxHighConnections
        expr: nginx_connections_active > 1000
        for: 5m
        labels:
          severity: warning
          category: loadbalancer
        annotations:
          summary: "Nginx活跃连接数过高"
          description: "Nginx实例 {{ $labels.instance }} 活跃连接数超过1000，当前值: {{ $value }}"
          runbook_url: "https://docs.inspi.ai/runbooks/nginx-high-connections"