// Shared React hooks
export { useToast } from './use-toast';
export { useAuth } from './useAuth';
export { useDebounce } from './useDebounce';
export { useErrorHandler } from './useErrorHandler';
export { useResponsive } from './useResponsive';
export { usePerformanceMonitor } from './usePerformanceMonitor';
export { useLazyLoad } from './useLazyLoad';
export { useInfiniteScroll } from './useInfiniteScroll';
export { useKeyboardNavigation } from './useKeyboardNavigation';
export { useFocusManagement } from './useFocusManagement';
export { useHoverEffects } from './useHoverEffects';
export { useTouch } from './useTouch';
export { useVirtualization } from './useVirtualization';
export { useAdaptiveTypography } from './useAdaptiveTypography';
export { useDataLazyLoad } from './useDataLazyLoad';
export { useLazyLoadPerformance } from './useLazyLoadPerformance';
export { useSEO } from './useSEO';
export { useApiError } from './useApiError';
